name: Snyk Container
on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-goof
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        load: true
        context: todolist-goof
        push: false
        tags: java-goof:latest
      
    - name: Run Snyk Container
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: java-goof:latest
